version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      all-actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/shiptalkers-app"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      shiptalkers-app-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/shiptalkers-scraper"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      shiptalkers-scraper-dependencies:
        patterns:
          - "*"
  
  - package-ecosystem: "cargo"
    directory: "/shiptalkers-lib"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      shiptalkers-lib-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      shiptalkers-common-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/scripts/slack_app_creation"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      slack_app_creation-dependencies:
        patterns:
          - "*"