frontend:
  - changed-files:
      - any-glob-to-any-file: 
          - "templates/**"
          - "src/website/**"

backend:
  - changed-files:
      - all-globs-to-all-files: 
          - "src/**"
          - "!src/website/**" # Safely excludes the website folder
  - changed-files:
      - any-glob-to-any-file:
          - "Cargo.toml"
          - "Cargo.lock"  

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "compose.dev.yml"
          - "compose.prod.yml"
          - "Dockerfile"
          - ".github/workflows/docker.yml"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "Cargo.toml"
          - "Cargo.lock"

utils:
  - changed-files:
      - any-glob-to-any-file:
          - "scripts/**"
          - "justfile"
