TRUNCATE TABLE
    slack_message_contents,
    slack_messages,
    slack_reactions,
    slack_consents,
    slack_identities,
    slack_channels,
    word_counts,
    word_totals,
    user_scores,
    channel_scores,
    daily_stats,
    message_count,
    scrape_checkpoints,
    thread_checkpoints,
    scraped_channels,
    scrape_sweep,
    users,
    linked_users,
    api_key_grants,
    api_keys,
    hackatime_spans,
    hackatime_connections,
    score_meta,
    backfill_meta,
    word_refresh_meta,
    stats_meta
RESTART IDENTITY CASCADE;
