name: Build shiptalkers-scraper

on:
  push:
    branches: [main]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - ".dockerignore"
      - "shiptalkers-scraper/**"
      - "shiptalkers-lib/**"
      - ".github/workflows/build-shiptalkers-scraper.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: deploy-shiptalkers-scraper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Coolify
        uses: SeradedStripes/coolify-deploy@v1.1
        with:
          coolify_url: 'https://coolify.kirze.de'
          coolify_app_uuid: 'nhtvnfcv6l8ewtqu5qune9pi&'
          coolify_token: ${{ secrets.COOLIFY_TOKEN }}
          build_image: 'true'
          build_image_name: 'shiptalkers-scraper'
          build_image_tag: 'latest'
          build_image_registry: 'ghcr.io/seradedstripes'
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          build_context: '.'
          dockerfile: './shiptalkers-scraper/Dockerfile'