name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - .env.example
      - justfile
      - .gitignore
      - .dockerignore
      - compose.dev.yml
      - compose.prod.yml
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - .env.example
      - justfile
      - .gitignore
      - .dockerignore
      - compose.dev.yml
      - compose.prod.yml
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runnner.os }}-rust-cache

      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Run tests
        run: cargo test --all-features