use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, exit};
use std::time::Duration;

use rand::Rng;
use rand::distributions::Alphanumeric;
use reqwest::Client;
use serde_json::{Value, json};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

const API: &str = "https://slack.com/api";

pub struct EnvEntry {
    pub comment: &'static str,
    pub key: String,
    pub value: String,
}

fn output_env_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(".env.output")
}

/// Next free numbered key for a list var, e.g. SLACK_BOT_TOKENS_2 when
/// SLACK_BOT_TOKENS_1 already exists. Each run creates a fresh app, so each
/// run's tokens get their own short line instead of one giant comma line.
fn next_list_key(existing: Option<&str>, base: &str) -> String {
    let mut max = 0u32;
    if let Some(text) = existing {
        let prefix = format!("{base}_");
        for line in text.lines() {
            if let Some((key, _)) = line.split_once('=')
                && let Some(rest) = key.trim().strip_prefix(&prefix)
                && let Ok(n) = rest.parse::<u32>()
            {
                max = max.max(n);
            }
        }
    }
    format!("{base}_{}", max + 1)
}

pub fn merge_env_output(existing: Option<&str>, entries: &[EnvEntry]) -> String {
    let mut lines: Vec<String> = match existing {
        Some(text) => text.lines().map(str::to_string).collect(),
        None => vec![
            "# Auto-generated by slack_app_creation for ship-talkers. Paste these".to_string(),
            "# values into the app's .env or its Coolify environment variables.".to_string(),
            String::new(),
        ],
    };
    let mut missing: Vec<&EnvEntry> = Vec::new();
    for entry in entries {
        let mut found = false;
        for line in lines.iter_mut() {
            let Some((key, _)) = line.split_once('=') else {
                continue;
            };
            if key.trim() == entry.key {
                if !entry.value.is_empty() {
                    *line = format!("{}={}", entry.key, entry.value);
                }
                found = true;
                break;
            }
        }
        if !found {
            missing.push(entry);
        }
    }
    if !missing.is_empty() {
        if lines.last().map(|l| !l.is_empty()).unwrap_or(true) {
            lines.push(String::new());
        }
        for entry in missing {
            lines.push(entry.comment.to_string());
            lines.push(format!("{}={}", entry.key, entry.value));
        }
    }
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

fn write_env_output(entries: &[EnvEntry]) -> Result<(), String> {
    let path = output_env_path();
    let existing = fs::read_to_string(&path).ok();
    let content = merge_env_output(existing.as_deref(), entries);
    fs::write(&path, content).map_err(|e| format!("failed to write {}: {e}", path.display()))?;
    println!("\nWrote app env to {}", path.display());
    Ok(())
}

fn app_env_entries(existing: Option<&str>, bot_token: &str, user_token: &str) -> Vec<EnvEntry> {
    vec![
        EnvEntry {
            comment: "# Bot token (SLACK_BOT_TOKENS); add more apps as _2, _3, ...",
            key: next_list_key(existing, "SLACK_BOT_TOKENS"),
            value: bot_token.to_string(),
        },
        EnvEntry {
            comment: "# User token (SLACK_USER_TOKENS); add more apps as _2, _3, ...",
            key: next_list_key(existing, "SLACK_USER_TOKENS"),
            value: user_token.to_string(),
        },
        EnvEntry {
            comment: "# App token (xapp-...), created under the app's App-Level Tokens page.",
            key: "SLACK_APP_TOKENS".to_string(),
            value: String::new(),
        },
    ]
}

fn usage() -> String {
    "Usage: slack_app_creation [manifest.json|manifest.yml]

Environment:
  SLACK_CONFIG_TOKEN          App configuration token (xoxe...), required.
  SLACK_CONFIG_REFRESH_TOKEN  Optional config refresh token; rotates the
                              config token first (config tokens expire after
                              12 hours).
  SLACK_INSTALL_PORT          Local callback port (default 8099).

Uses manifest.yml (in the same directory as .env.example) unless another
manifest file is passed as an argument. Prints the app credentials plus the
bot and user tokens after the OAuth install finishes, and writes them to
.env.output (next to the manifest) for the Rust app. Re-running updates
existing keys in place and appends any new ones. The app-level token
(xapp...) is created separately under the app's App-Level Tokens page; the
manifest enables Socket Mode.
"
    .to_string()
}

fn default_manifest_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("manifest.yml")
}

fn load_manifest(path: &Path) -> Result<Value, String> {
    let text = fs::read_to_string(path)
        .map_err(|e| format!("manifest file not found: {}: {e}", path.display()))?;
    let value = serde_json::from_str(&text)
        .or_else(|_| serde_yaml::from_str::<Value>(&text))
        .map_err(|e| {
            format!(
                "manifest is not valid JSON or YAML ({}): {e}",
                path.display()
            )
        })?;
    if !value.is_object() {
        return Err(format!(
            "manifest must be a mapping ({}): {value}",
            path.display()
        ));
    }
    Ok(value)
}

fn slack_error(prefix: &str, resp: &Value) -> String {
    let mut msg = format!("{prefix} failed: {}", resp["error"]);
    if let Some(errors) = resp["errors"].as_array() {
        for e in errors {
            msg.push_str(&format!(
                "\n  {}: {}",
                e["pointer"].as_str().unwrap_or("(no pointer)"),
                e["message"].as_str().unwrap_or("(no message)")
            ));
        }
    }
    msg
}

fn inject_redirect(manifest: &mut Value, redirect_uri: &str) {
    let mut redirects = extract_strings(&manifest["oauth_config"]["redirect_urls"]);
    if !redirects.iter().any(|r| r == redirect_uri) {
        redirects.push(redirect_uri.to_string());
    }
    manifest["oauth_config"]["redirect_urls"] = json!(redirects);
}

fn var(name: &str) -> Option<String> {
    env::var(name).ok().filter(|v| !v.is_empty())
}

fn extract_strings(v: &Value) -> Vec<String> {
    v.as_array()
        .map(|a| {
            a.iter()
                .filter_map(|s| s.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default()
}

#[tokio::main]
async fn main() {
    dotenvy::dotenv().ok();
    if let Err(e) = run().await {
        eprintln!("error: {e}");
        exit(1);
    }
}

async fn run() -> Result<(), String> {
    let manifest_arg = env::args().nth(1);
    if matches!(manifest_arg.as_deref(), Some("-h") | Some("--help")) {
        print!("{}", usage());
        return Ok(());
    }

    let config_token = var("SLACK_CONFIG_TOKEN").ok_or_else(|| {
        "SLACK_CONFIG_TOKEN is required (app configuration token, xoxe...); generate one \
         at https://api.slack.com/apps -> your app -> App Configuration Tokens"
            .to_string()
    })?;
    if !config_token.starts_with("xoxe") {
        eprintln!("warning: SLACK_CONFIG_TOKEN does not look like a config token (xoxe...)");
    }

    let port: u16 = match var("SLACK_INSTALL_PORT") {
        Some(p) => p
            .parse()
            .map_err(|_| format!("SLACK_INSTALL_PORT must be a number, got: {p}"))?,
        None => 8099,
    };
    let redirect_uri = format!("http://localhost:{port}/callback");
    let state: String = rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .take(24)
        .map(char::from)
        .collect();

    let client = Client::new();

    let config_token = if let Some(refresh) = var("SLACK_CONFIG_REFRESH_TOKEN") {
        println!("Rotating config token...");
        let resp: Value = client
            .post(format!("{API}/tooling.tokens.rotate"))
            .form(&[("refresh_token", refresh.as_str())])
            .send()
            .await
            .map_err(|e| e.to_string())?
            .json()
            .await
            .map_err(|e| e.to_string())?;
        if resp["ok"] != true {
            return Err(format!("token rotation failed: {}", resp["error"]));
        }
        resp["token"].as_str().unwrap_or("").to_string()
    } else {
        config_token
    };

    let manifest_path = manifest_arg
        .map(PathBuf::from)
        .unwrap_or_else(default_manifest_path);
    let mut manifest = load_manifest(&manifest_path)?;
    inject_redirect(&mut manifest, &redirect_uri);

    println!("Validating manifest...");
    let resp: Value = client
        .post(format!("{API}/apps.manifest.validate"))
        .bearer_auth(&config_token)
        .json(&json!({ "manifest": manifest.to_string() }))
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    if resp["ok"] != true {
        return Err(slack_error("apps.manifest.validate", &resp));
    }
    if let Some(warnings) = resp["warnings"].as_array() {
        for w in warnings {
            eprintln!("warning: {w}");
        }
    }

    println!("Creating app from manifest...");
    let resp: Value = client
        .post(format!("{API}/apps.manifest.create"))
        .bearer_auth(&config_token)
        .json(&json!({ "manifest": manifest.to_string() }))
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    if resp["ok"] != true {
        return Err(slack_error("apps.manifest.create", &resp));
    }
    let app_id = resp["app_id"].as_str().unwrap_or("").to_string();
    let client_id = resp["credentials"]["client_id"]
        .as_str()
        .unwrap_or("")
        .to_string();
    let client_secret = resp["credentials"]["client_secret"]
        .as_str()
        .unwrap_or("")
        .to_string();
    let signing_secret = resp["credentials"]["signing_secret"]
        .as_str()
        .unwrap_or("")
        .to_string();
    let app_name = manifest["display_information"]["name"]
        .as_str()
        .unwrap_or("")
        .to_string();
    println!("App {app_id} created ({app_name})");

    let listener = TcpListener::bind(("127.0.0.1", port))
        .await
        .map_err(|e| e.to_string())?;

    let bot_scope = extract_strings(&manifest["oauth_config"]["scopes"]["bot"]).join(",");
    let user_scope = extract_strings(&manifest["oauth_config"]["scopes"]["user"]).join(",");
    let auth_url = reqwest::Url::parse_with_params(
        "https://slack.com/oauth/v2/authorize",
        &[
            ("client_id", client_id.as_str()),
            ("scope", &bot_scope),
            ("user_scope", &user_scope),
            ("redirect_uri", redirect_uri.as_str()),
            ("state", state.as_str()),
        ],
    )
    .map_err(|e| e.to_string())?;

    println!("\nAuthorize the app here:");
    println!("  {auth_url}\n");

    if Command::new("xdg-open")
        .arg(auth_url.as_str())
        .spawn()
        .is_err()
    {
        let _ = Command::new("open").arg(auth_url.as_str()).spawn();
    }

    println!("Waiting for authorization (the code expires after 10 minutes)...");
    let (mut socket, _) =
        match tokio::time::timeout(Duration::from_secs(600), listener.accept()).await {
            Err(_) => return Err("timed out waiting for authorization".to_string()),
            Ok(Err(e)) => return Err(format!("listener error: {e}")),
            Ok(Ok(conn)) => conn,
        };

    let mut buf = Vec::new();
    let mut byte = [0u8; 1];
    loop {
        match socket.read(&mut byte).await {
            Ok(0) => break,
            Ok(_) => {
                if byte[0] == b'\n' {
                    break;
                }
                buf.push(byte[0]);
            }
            Err(e) => return Err(format!("callback read error: {e}")),
        }
    }
    let line = String::from_utf8_lossy(&buf);
    let path = line.split(' ').nth(1).unwrap_or("");
    let query = path.split('?').nth(1).unwrap_or("");
    let params: HashMap<String, String> = url::form_urlencoded::parse(query.as_bytes())
        .into_owned()
        .collect();
    let cb_code = params.get("code").cloned().unwrap_or_default();
    let cb_state = params.get("state").cloned().unwrap_or_default();
    let cb_error = params.get("error").cloned().unwrap_or_default();

    let body = if cb_error.is_empty() {
        "<h1>Authorized! You can close this window.</h1>"
    } else {
        "<h1>Authorization failed. You can close this window.</h1>"
    };
    let _ = socket
        .write_all(
            format!(
                "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
                body.len()
            )
            .as_bytes(),
        )
        .await;

    if !cb_error.is_empty() {
        return Err(format!("authorization failed: {cb_error}"));
    }
    if cb_code.is_empty() {
        return Err("no code received in callback".to_string());
    }
    if cb_state != state {
        return Err("state mismatch, aborting (possible CSRF)".to_string());
    }

    println!("Exchanging code for tokens...");
    let resp: Value = client
        .post(format!("{API}/oauth.v2.access"))
        .form(&[
            ("client_id", client_id.as_str()),
            ("client_secret", client_secret.as_str()),
            ("code", cb_code.as_str()),
            ("redirect_uri", redirect_uri.as_str()),
        ])
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    if resp["ok"] != true {
        return Err(format!("oauth.v2.access failed: {}", resp["error"]));
    }

    let bot_token = resp["access_token"].as_str().unwrap_or("").to_string();
    let bot_user_id = resp["bot_user_id"].as_str().unwrap_or("").to_string();
    let user_token = resp["authed_user"]["access_token"]
        .as_str()
        .unwrap_or("")
        .to_string();
    let user_id = resp["authed_user"]["id"].as_str().unwrap_or("").to_string();
    let team_id = resp["team"]["id"].as_str().unwrap_or("").to_string();
    let team_name = resp["team"]["name"].as_str().unwrap_or("").to_string();

    println!();
    println!("======================");
    println!(" App installed");
    println!("======================");
    println!("App name:       {app_name}");
    println!("App ID:         {app_id}");
    println!("Manage app:     https://api.slack.com/apps/{app_id}");
    println!("Workspace:      {team_name} ({team_id})");
    println!();
    println!("Bot token (SLACK_BOT_TOKENS):   {bot_token}");
    println!("Bot user ID:                    {bot_user_id}");
    println!("User token (SLACK_USER_TOKENS): {user_token}");
    println!("User ID:                        {user_id}");
    println!("App token (SLACK_APP_TOKENS):   create under App-Level Tokens:");
    println!("                                https://api.slack.com/apps/{app_id}");
    println!();
    println!("OAuth credentials (only needed for the app page):");
    println!("  client_id:     {client_id}");
    println!("  client_secret: {client_secret}");
    println!("  signing_secret:{signing_secret}");
    println!();
    println!("Notes:");
    println!("  - The app token (xapp-...) cannot be generated via the API; the manifest");
    println!("    enables Socket Mode, so create one under the app's App-Level Tokens page.");
    let cfg = &config_token[..12.min(config_token.len())];
    println!("  - The config token ({cfg}...) expires 12 hours after it is generated;");
    println!("    rotate it with SLACK_CONFIG_REFRESH_TOKEN when needed.");

    write_env_output(&app_env_entries(fs::read_to_string(output_env_path()).ok().as_deref(), &bot_token, &user_token))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_default_manifest() {
        let manifest = load_manifest(&default_manifest_path()).unwrap();
        assert!(
            !manifest["display_information"]["name"]
                .as_str()
                .unwrap_or("")
                .is_empty()
        );
        assert!(!extract_strings(&manifest["oauth_config"]["scopes"]["bot"]).is_empty());
    }

    #[test]
    fn injects_redirect_url() {
        let mut manifest = load_manifest(&default_manifest_path()).unwrap();
        inject_redirect(&mut manifest, "http://localhost:8099/callback");
        let urls = extract_strings(&manifest["oauth_config"]["redirect_urls"]);
        assert!(urls.contains(&"http://localhost:8099/callback".to_string()));
        inject_redirect(&mut manifest, "http://localhost:8099/callback");
        assert_eq!(
            extract_strings(&manifest["oauth_config"]["redirect_urls"]).len(),
            1
        );
    }

    #[test]
    fn writes_fresh_env_output_with_header() {
        let entries = app_env_entries(None, "xoxb-a", "xoxp-b");
        let out = merge_env_output(None, &entries);
        assert!(out.starts_with("# Auto-generated by slack_app_creation"));
        assert!(out.contains("SLACK_BOT_TOKENS_1=xoxb-a\n"));
        assert!(out.contains("SLACK_USER_TOKENS_1=xoxp-b\n"));
        assert!(out.contains("SLACK_APP_TOKENS=\n"));
    }

    #[test]
    fn rerun_uses_next_numbered_key() {
        let existing = "SLACK_MAIN_CHANNEL=C123\nSLACK_BOT_TOKENS_1=xoxb-1\nSLACK_USER_TOKENS_1=xoxp-1\n";
        let entries = app_env_entries(Some(existing), "xoxb-2", "xoxp-2");
        assert_eq!(entries[0].key, "SLACK_BOT_TOKENS_2");
        assert_eq!(entries[1].key, "SLACK_USER_TOKENS_2");
        let out = merge_env_output(Some(existing), &entries);
        assert!(out.contains("SLACK_BOT_TOKENS_1=xoxb-1\n"));
        assert!(out.contains("SLACK_BOT_TOKENS_2=xoxb-2\n"));
        assert!(out.contains("SLACK_USER_TOKENS_2=xoxp-2\n"));
        assert!(out.contains("SLACK_MAIN_CHANNEL=C123\n"));
        assert!(out.contains("SLACK_APP_TOKENS=\n"));
    }

    #[test]
    fn next_list_key_counts_existing_variants() {
        assert_eq!(next_list_key(None, "SLACK_BOT_TOKENS"), "SLACK_BOT_TOKENS_1");
        let existing = "SLACK_BOT_TOKENS_3=x\nSLACK_BOT_TOKENS_1=y\n";
        assert_eq!(
            next_list_key(Some(existing), "SLACK_BOT_TOKENS"),
            "SLACK_BOT_TOKENS_4"
        );
    }

    #[test]
    fn rerun_keeps_user_filled_empty_values() {
        let entries = app_env_entries(None, "xoxb-new", "xoxp-new");
        let existing = "SLACK_APP_TOKENS=xapp-user-filled\n";
        let out = merge_env_output(Some(existing), &entries);
        assert!(out.contains("SLACK_APP_TOKENS=xapp-user-filled\n"));
    }
}
